inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rbs_inline

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/LineLength:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
