plugins:
  - rubocop-rbs_inline

AllCops:
  TargetRubyVersion: 3.2

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
